services:
  chaser-cf:
    build:
      context: docker
      dockerfile: chaser-cf.Dockerfile
    image: chaser-cf:local
    restart: unless-stopped
    shm_size: 2gb

  chaser-resolverr:
    build:
      context: .
    image: chaser-resolverr-rs:local
    restart: unless-stopped
    depends_on:
      - chaser-cf
    environment:
      - CHASER_URL=http://chaser-cf:3000
    volumes:
      - ./data:/data
    ports:
      - "8191:8191"
